### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kazankage** [learn-co-curriculum/programming-univbasics-expression-and-evaluation-defined#3]
There is a typo in the paragraph under the Wikipedia definition. The second sentence should read, "That should align with your* experience of having a conversation with IRB from the previous lesson."

![Typo](https://user-images.githubusercontent.com/11214370/63460837-2cb19d00-c40c-11e9-92db-883340053369.png)

**Comment by sgharms** [comment]
Thanks! Fixed.
